name: layer0 publish

on:
  push:
    branches: main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://registry.npmjs.org/
          cache: "npm"
          cache-dependency-path: package-lock.json
      - name: publish package
        env:
          SKIP_PREFLIGHT_CHECK: true
        run: |
          npm i
          npm i -g @layer0/cli
          npm run build
          layer0 deploy  --token=${{secrets.layer0DeployToken}}
